# Generated by Django 4.2.7 on 2023-11-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box_app', '0002_alter_boxingclass_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxingclassmembership',
            name='boxing_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='box_app.boxingclass'),
        ),
        migrations.AlterField(
            model_name='boxingclassmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to='box_app.student'),
        ),
    ]
