# Generated by Django 4.2.7 on 2023-11-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('box_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxingclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box_app.trainer'),
        ),
    ]
